### ISSUE TITLE
How to config IFSL?

### ISSUE THREAD

**Issue by Surflyan** [yue-zhongqi/ifsl#1]
hello, your job was nice. I try to run your code in MTL with "--config=mini_5_resnet_d" ，are you sure the current config is rigtht? how to get into mtl.py 68 line.    
 ‘’‘       
 if args.param.learner == "IFSL":
                self.base_learner = IFSL(args.way, args.shot, self.pretrain, **args.param.ifsl_params)
’‘’
There seems to be a bug in this mtl.py 68 line. ” No IFSL“. Thanks

**Comment by yue-zhongqi** [comment]
Hi. That part of the code is not run in IFSL.  IFSL runs with line 167: learner = DeconfoundedLearner(pretrain=self.pretrain, **self.args.param.ifsl_params)
