### ISSUE TITLE
Where is the code for function c = g(x, d) in the paper?

### ISSUE THREAD

**Issue by Kyfafyd** [yue-zhongqi/ifsl#2]
Thanks for amazing work and open source code.

However, I have a question:
In supplemental materials, for fine-tuning+IFSL, you calculate `c = g(x, d)`, I wonder where is this function in your code?
Thanks very much and looking forward to your reply!

**Comment by yue-zhongqi** [comment]
Hi!
You can check this line where features are split into n parts (feature-wise adjustment) and then concatenated with pre-trained class-wise weighted mean (class-wise adjustment).
https://github.com/yue-zhongqi/ifsl/blob/2fc15a8233c9ec30080b9eaed6e9c10dcc85e695/MAML_MN_FT/methods/meta_toolkits.py#L156
The c=g(x,d) is implemented differently under different adjustment strategies.

**Comment by Kyfafyd** [comment]
> Hi!
> You can check this line where features are split into n parts (feature-wise adjustment) and then concatenated with pre-trained class-wise weighted mean (class-wise adjustment).
> https://github.com/yue-zhongqi/ifsl/blob/2fc15a8233c9ec30080b9eaed6e9c10dcc85e695/MAML_MN_FT/methods/meta_toolkits.py#L156
> 
> 
> The c=g(x,d) is implemented differently under different adjustment strategies.

Thanks very much
